version: '3.8'

services:
  db:
    image: postgres:15
    container_name: orders-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: orders-app
    ports:
      - "8000:8000"   # REST API
      - "50051:50051" # gRPC
      - "8080:8080"   # GraphQL
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=orders

volumes:
  postgres_data:
